data = (
    (0,
     {'valmin': 1,
      'valmax': 15,
      'valinit': 8,
      'label': "Outer gear radius"}),
    (1,
     {'valmin': 1,
      'valmax': 15,
      'valinit': 5,
      'label': "Inner gear equiv. radius"}),
    (2,
     {'valmin': 0.,
      'valmax': 1.,
      'valinit': .2,
      'label': "Squared eccentricity"}),
    (3,
     {'valmin': 0.,
      'valmax': 15,
      'valinit': 2.,
      'label': "Hole distance"})
    )
